// Dropdown options for onboarding form

export const UNION_STATUS_OPTIONS = [
  { value: "sag-aftra", label: "SAG-AFTRA" },
  { value: "equity", label: "Actors' Equity Association" },
  { value: "afm", label: "American Federation of Musicians" },
  { value: "agma", label: "American Guild of Musical Artists" },
  { value: "agva", label: "American Guild of Variety Artists" },
  { value: "dga", label: "Directors Guild of America" },
  { value: "wga", label: "Writers Guild of America" },
  { value: "iatse", label: "International Alliance of Theatrical Stage Employees" },
  { value: "non-union", label: "Non-Union" },
  { value: "eligible", label: "Union Eligible" },
];

export const LANGUAGE_OPTIONS = [
  { value: "english", label: "English" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "italian", label: "Italian" },
  { value: "portuguese", label: "Portuguese" },
  { value: "russian", label: "Russian" },
  { value: "mandarin", label: "Mandarin Chinese" },
  { value: "cantonese", label: "Cantonese" },
  { value: "japanese", label: "Japanese" },
  { value: "korean", label: "Korean" },
  { value: "arabic", label: "Arabic" },
  { value: "hindi", label: "Hindi" },
  { value: "dutch", label: "Dutch" },
  { value: "swedish", label: "Swedish" },
  { value: "norwegian", label: "Norwegian" },
  { value: "danish", label: "Danish" },
  { value: "finnish", label: "Finnish" },
  { value: "polish", label: "Polish" },
  { value: "czech", label: "Czech" },
  { value: "hungarian", label: "Hungarian" },
  { value: "greek", label: "Greek" },
  { value: "hebrew", label: "Hebrew" },
  { value: "turkish", label: "Turkish" },
  { value: "thai", label: "Thai" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "tagalog", label: "Tagalog" },
  { value: "urdu", label: "Urdu" },
  { value: "bengali", label: "Bengali" },
  { value: "punjabi", label: "Punjabi" },
];

export const ACCENT_OPTIONS = [
  { value: "american-general", label: "American General" },
  { value: "british-rp", label: "British RP" },
  { value: "cockney", label: "Cockney" },
  { value: "scottish", label: "Scottish" },
  { value: "irish", label: "Irish" },
  { value: "welsh", label: "Welsh" },
  { value: "australian", label: "Australian" },
  { value: "canadian", label: "Canadian" },
  { value: "new-york", label: "New York" },
  { value: "southern-us", label: "Southern US" },
  { value: "boston", label: "Boston" },
  { value: "chicago", label: "Chicago" },
  { value: "texas", label: "Texas" },
  { value: "california", label: "California" },
  { value: "midwest", label: "Midwest" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "italian", label: "Italian" },
  { value: "spanish", label: "Spanish" },
  { value: "russian", label: "Russian" },
  { value: "indian", label: "Indian" },
  { value: "jamaican", label: "Jamaican" },
  { value: "south-african", label: "South African" },
];

export const INSTRUMENT_OPTIONS = [
  { value: "piano", label: "Piano" },
  { value: "guitar", label: "Guitar" },
  { value: "violin", label: "Violin" },
  { value: "drums", label: "Drums" },
  { value: "bass", label: "Bass" },
  { value: "saxophone", label: "Saxophone" },
  { value: "trumpet", label: "Trumpet" },
  { value: "flute", label: "Flute" },
  { value: "clarinet", label: "Clarinet" },
  { value: "cello", label: "Cello" },
  { value: "viola", label: "Viola" },
  { value: "harmonica", label: "Harmonica" },
  { value: "banjo", label: "Banjo" },
  { value: "mandolin", label: "Mandolin" },
  { value: "ukulele", label: "Ukulele" },
  { value: "keyboard", label: "Keyboard" },
  { value: "electric-guitar", label: "Electric Guitar" },
  { value: "acoustic-guitar", label: "Acoustic Guitar" },
  { value: "trombone", label: "Trombone" },
  { value: "french-horn", label: "French Horn" },
  { value: "oboe", label: "Oboe" },
  { value: "bassoon", label: "Bassoon" },
  { value: "harp", label: "Harp" },
  { value: "xylophone", label: "Xylophone" },
  { value: "marimba", label: "Marimba" },
];

export const GENRE_OPTIONS = [
  { value: "pop", label: "Pop" },
  { value: "rock", label: "Rock" },
  { value: "jazz", label: "Jazz" },
  { value: "classical", label: "Classical" },
  { value: "country", label: "Country" },
  { value: "blues", label: "Blues" },
  { value: "folk", label: "Folk" },
  { value: "electronic", label: "Electronic" },
  { value: "hip-hop", label: "Hip-Hop" },
  { value: "rap", label: "Rap" },
  { value: "r-and-b", label: "R&B" },
  { value: "soul", label: "Soul" },
  { value: "funk", label: "Funk" },
  { value: "reggae", label: "Reggae" },
  { value: "punk", label: "Punk" },
  { value: "metal", label: "Metal" },
  { value: "indie", label: "Indie" },
  { value: "alternative", label: "Alternative" },
  { value: "gospel", label: "Gospel" },
  { value: "broadway", label: "Broadway" },
  { value: "opera", label: "Opera" },
  { value: "world", label: "World Music" },
];

export const AFFILIATION_OPTIONS = [
  { value: "backstage", label: "Backstage" },
  { value: "casting-networks", label: "Casting Networks" },
  { value: "actors-access", label: "Actors Access" },
  { value: "imdb-pro", label: "IMDb Pro" },
  { value: "mandy-network", label: "Mandy Network" },
  { value: "spotlight", label: "Spotlight" },
  { value: "star-now", label: "Star Now" },
  { value: "talent-house", label: "Talent House" },
  { value: "model-mayhem", label: "Model Mayhem" },
  { value: "voices-com", label: "Voices.com" },
  { value: "voice123", label: "Voice123" },
  { value: "casting-crane", label: "Casting Crane" },
  { value: "explore-talent", label: "Explore Talent" },
  { value: "talent-manager", label: "Talent Manager Representation" },
  { value: "agent-representation", label: "Agent Representation" },
];

export const STUNT_OPTIONS = [
  { value: "martial-arts", label: "Martial Arts" },
  { value: "sword-fighting", label: "Sword Fighting" },
  { value: "stage-combat", label: "Stage Combat" },
  { value: "motorcycle-riding", label: "Motorcycle Riding" },
  { value: "horseback-riding", label: "Horseback Riding" },
  { value: "rock-climbing", label: "Rock Climbing" },
  { value: "skydiving", label: "Skydiving" },
  { value: "scuba-diving", label: "Scuba Diving" },
  { value: "car-racing", label: "Car Racing" },
  { value: "motorcycle-racing", label: "Motorcycle Racing" },
  { value: "fire-stunts", label: "Fire Stunts" },
  { value: "water-stunts", label: "Water Stunts" },
  { value: "high-falls", label: "High Falls" },
  { value: "wire-work", label: "Wire Work" },
  { value: "gymnastics", label: "Gymnastics" },
  { value: "parkour", label: "Parkour" },
  { value: "free-running", label: "Free Running" },
  { value: "precision-driving", label: "Precision Driving" },
  { value: "boat-driving", label: "Boat Driving" },
  { value: "aircraft-piloting", label: "Aircraft Piloting" },
];

export const ACTIVITY_OPTIONS = [
  { value: "horseback-riding", label: "Horseback Riding" },
  { value: "car-racing", label: "Car Racing" },
  { value: "motorcycle-racing", label: "Motorcycle Racing" },
  { value: "skiing", label: "Skiing" },
  { value: "snowboarding", label: "Snowboarding" },
  { value: "surfing", label: "Surfing" },
  { value: "swimming", label: "Swimming" },
  { value: "tennis", label: "Tennis" },
  { value: "golf", label: "Golf" },
  { value: "basketball", label: "Basketball" },
  { value: "soccer", label: "Soccer" },
  { value: "football", label: "Football" },
  { value: "baseball", label: "Baseball" },
  { value: "volleyball", label: "Volleyball" },
  { value: "cycling", label: "Cycling" },
  { value: "running", label: "Running" },
  { value: "yoga", label: "Yoga" },
  { value: "pilates", label: "Pilates" },
  { value: "dance", label: "Dance" },
  { value: "ballet", label: "Ballet" },
  { value: "martial-arts", label: "Martial Arts" },
  { value: "boxing", label: "Boxing" },
  { value: "wrestling", label: "Wrestling" },
  { value: "gymnastics", label: "Gymnastics" },
  { value: "rock-climbing", label: "Rock Climbing" },
  { value: "hiking", label: "Hiking" },
  { value: "camping", label: "Camping" },
  { value: "fishing", label: "Fishing" },
  { value: "sailing", label: "Sailing" },
  { value: "kayaking", label: "Kayaking" },
];

export const DANCING_STYLES = [
  { value: "ballet", label: "Ballet" },
  { value: "jazz", label: "Jazz" },
  { value: "hip-hop", label: "Hip-Hop" },
  { value: "contemporary", label: "Contemporary" },
  { value: "modern", label: "Modern" },
  { value: "tap", label: "Tap" },
  { value: "ballroom", label: "Ballroom" },
  { value: "latin", label: "Latin" },
  { value: "salsa", label: "Salsa" },
  { value: "tango", label: "Tango" },
  { value: "waltz", label: "Waltz" },
  { value: "foxtrot", label: "Foxtrot" },
  { value: "swing", label: "Swing" },
  { value: "breakdancing", label: "Breakdancing" },
  { value: "street-dance", label: "Street Dance" },
  { value: "krump", label: "Krump" },
  { value: "popping", label: "Popping" },
  { value: "locking", label: "Locking" },
  { value: "flamenco", label: "Flamenco" },
  { value: "belly-dance", label: "Belly Dance" },
  { value: "pole-dancing", label: "Pole Dancing" },
  { value: "irish-step", label: "Irish Step" },
  { value: "line-dancing", label: "Line Dancing" },
  { value: "musical-theater", label: "Musical Theater" },
];

export const DRIVING_LICENSES = [
  { value: "regular", label: "Regular Driver's License" },
  { value: "motorcycle", label: "Motorcycle License" },
  { value: "cdl", label: "Commercial Driver's License (CDL)" },
  { value: "chauffeur", label: "Chauffeur License" },
  { value: "boat", label: "Boat License" },
  { value: "pilot", label: "Pilot License" },
  { value: "helicopter", label: "Helicopter License" },
  { value: "international", label: "International Driving Permit" },
  { value: "taxi", label: "Taxi License" },
  { value: "uber-lyft", label: "Uber/Lyft Approved" },
];

export const EYE_COLOR_OPTIONS = [
  { value: "brown", label: "Brown" },
  { value: "blue", label: "Blue" },
  { value: "green", label: "Green" },
  { value: "hazel", label: "Hazel" },
  { value: "amber", label: "Amber" },
  { value: "gray", label: "Gray" },
  { value: "violet", label: "Violet" },
  { value: "heterochromia", label: "Heterochromia" },
];

export const HAIR_COLOR_OPTIONS = [
  { value: "blonde", label: "Blonde" },
  { value: "brown", label: "Brown" },
  { value: "black", label: "Black" },
  { value: "red", label: "Red" },
  { value: "auburn", label: "Auburn" },
  { value: "gray", label: "Gray" },
  { value: "white", label: "White" },
  { value: "strawberry-blonde", label: "Strawberry Blonde" },
  { value: "dirty-blonde", label: "Dirty Blonde" },
  { value: "light-brown", label: "Light Brown" },
  { value: "dark-brown", label: "Dark Brown" },
  { value: "salt-and-pepper", label: "Salt and Pepper" },
  { value: "bald", label: "Bald" },
];

export const VOCAL_RANGE_OPTIONS = [
  { value: "soprano", label: "Soprano" },
  { value: "mezzo-soprano", label: "Mezzo-Soprano" },
  { value: "alto", label: "Alto" },
  { value: "tenor", label: "Tenor" },
  { value: "baritone", label: "Baritone" },
  { value: "bass", label: "Bass" },
  { value: "countertenor", label: "Countertenor" },
  { value: "contralto", label: "Contralto" },
  { value: "coloratura", label: "Coloratura" },
  { value: "dramatic", label: "Dramatic" },
  { value: "lyric", label: "Lyric" },
  { value: "belting", label: "Belting" },
  { value: "mixed-voice", label: "Mixed Voice" },
];

export const WARDROBE_OPTIONS = [
  { value: "business-formal", label: "Business Formal" },
  { value: "business-casual", label: "Business Casual" },
  { value: "cocktail", label: "Cocktail" },
  { value: "evening-wear", label: "Evening Wear" },
  { value: "casual", label: "Casual" },
  { value: "athletic", label: "Athletic" },
  { value: "vintage", label: "Vintage" },
  { value: "period-costume", label: "Period Costume" },
  { value: "uniform", label: "Uniform" },
  { value: "scrubs", label: "Scrubs" },
  { value: "suit", label: "Suit" },
  { value: "tuxedo", label: "Tuxedo" },
  { value: "wedding-dress", label: "Wedding Dress" },
  { value: "swimwear", label: "Swimwear" },
  { value: "lingerie", label: "Lingerie" },
  { value: "dance-wear", label: "Dance Wear" },
  { value: "workout-clothes", label: "Workout Clothes" },
  { value: "leather", label: "Leather" },
  { value: "punk", label: "Punk" },
  { value: "gothic", label: "Gothic" },
  { value: "bohemian", label: "Bohemian" },
  { value: "preppy", label: "Preppy" },
  { value: "hipster", label: "Hipster" },
  { value: "cowboy", label: "Cowboy/Western" },
];