-- Add new talent categories: Writer, Director, Cinematographer
-- These will be comprehensive questions with options and proper categorization

-- Writer Questions (20 questions with comprehensive options)
INSERT INTO profile_questions (talent_type, question, field_name, field_type, options, "order", required, active) VALUES
('writer', 'What type of writing do you specialize in?', 'writing_specialization', 'select', ARRAY['Screenwriting', 'Novel Writing', 'Short Stories', 'Poetry', 'Journalism', 'Technical Writing', 'Copywriting', 'Content Writing', 'Article Writing', 'Magazine Writing', 'Blog Writing', 'Academic Writing', 'Grant Writing', 'Business Writing', 'Creative Writing', 'Other'], 1, true, true),
('writer', 'What genres do you write in? (Select all that apply)', 'writing_genres', 'checkbox', ARRAY['Drama', 'Comedy', 'Thriller', 'Horror', 'Romance', 'Science Fiction', 'Fantasy', 'Mystery', 'Action', 'Documentary', 'Biography', 'Historical Fiction', 'Literary Fiction', 'Young Adult', 'Children''s', 'Non-Fiction', 'Self-Help', 'Business', 'Travel', 'Health & Wellness', 'Other'], 2, true, true),
('writer', 'How many years of writing experience do you have?', 'writing_experience_years', 'select', ARRAY['Less than 1 year', '1-2 years', '3-5 years', '6-10 years', '11-15 years', '16-20 years', 'More than 20 years'], 3, true, true),
('writer', 'What is your highest level of education in writing or related fields?', 'writing_education', 'select', ARRAY['High School', 'Some College', 'Bachelor''s Degree', 'Master''s Degree (MFA/MA)', 'PhD/Doctorate', 'Professional Certification', 'Self-Taught', 'Writing Workshops/Courses'], 4, true, true),
('writer', 'Have you been published or produced before?', 'writing_published', 'select', ARRAY['Yes, traditionally published', 'Yes, self-published', 'Yes, produced (film/TV)', 'Yes, produced (theater)', 'Yes, published online', 'No, but submitted work', 'No, not yet published'], 5, true, true),
('writer', 'What writing software/tools do you use?', 'writing_tools', 'checkbox', ARRAY['Final Draft', 'WriterDuet', 'Celtx', 'Scrivener', 'Microsoft Word', 'Google Docs', 'Fountain', 'Highland', 'Movie Magic Screenwriter', 'Adobe Story', 'Trelby', 'Other'], 6, false, true),
('writer', 'Are you available for collaboration projects?', 'writing_collaboration', 'select', ARRAY['Yes, always open to collaboration', 'Yes, but selective about projects', 'Occasionally', 'Prefer to work alone', 'Not interested in collaboration'], 7, true, true),
('writer', 'What is your typical turnaround time for a feature-length screenplay?', 'screenplay_turnaround', 'select', ARRAY['1-2 weeks', '3-4 weeks', '1-2 months', '3-4 months', '5-6 months', 'More than 6 months', 'Depends on project complexity'], 8, false, true),
('writer', 'Do you offer script coverage or editing services?', 'script_services', 'checkbox', ARRAY['Script Coverage', 'Script Editing', 'Script Polishing', 'Story Consulting', 'Character Development', 'Dialogue Polishing', 'Structure Analysis', 'Genre Consultation', 'Pitch Deck Creation', 'Treatment Writing'], 9, false, true),
('writer', 'What is your experience with adaptation work?', 'adaptation_experience', 'select', ARRAY['Extensive experience', 'Some experience', 'Limited experience', 'No experience but interested', 'Not interested in adaptations'], 10, false, true),
('writer', 'Are you a member of any writing organizations?', 'writing_organizations', 'checkbox', ARRAY['Writers Guild of America (WGA)', 'International Screenwriters'' Association', 'Authors Guild', 'Society of Children''s Book Writers', 'Romance Writers of America', 'Mystery Writers of America', 'Science Fiction Writers of America', 'Horror Writers Association', 'Local Writing Groups', 'Online Writing Communities', 'Other'], 11, false, true),
('writer', 'What is your preferred working environment?', 'writing_environment', 'select', ARRAY['Home office', 'Coffee shops', 'Library', 'Co-working space', 'Outdoors', 'Quiet spaces', 'Collaborative spaces', 'Flexible/anywhere'], 12, false, true),
('writer', 'Do you have experience writing for specific mediums?', 'writing_mediums', 'checkbox', ARRAY['Feature Films', 'Television Series', 'Web Series', 'Short Films', 'Theater', 'Radio', 'Podcasts', 'Video Games', 'Interactive Media', 'Virtual Reality', 'Commercials', 'Music Videos'], 13, false, true),
('writer', 'What is your approach to character development?', 'character_development_approach', 'textarea', NULL, 14, false, true),
('writer', 'Are you comfortable writing in multiple voices/perspectives?', 'multiple_perspectives', 'select', ARRAY['Very comfortable', 'Somewhat comfortable', 'Limited experience', 'Prefer single perspective', 'Not comfortable'], 15, false, true),
('writer', 'Do you have experience with writing for specific demographics?', 'target_demographics', 'checkbox', ARRAY['Children (0-12)', 'Teenagers (13-17)', 'Young Adults (18-25)', 'Adults (26-54)', 'Seniors (55+)', 'International Audiences', 'Niche Communities', 'General Audiences'], 16, false, true),
('writer', 'What is your experience with research for writing projects?', 'research_experience', 'select', ARRAY['Extensive research background', 'Moderate research skills', 'Basic research abilities', 'Limited research experience', 'Prefer projects requiring minimal research'], 17, false, true),
('writer', 'Are you available for script doctoring or rewriting?', 'script_doctoring', 'select', ARRAY['Yes, specialized in script doctoring', 'Yes, available for rewrites', 'Occasionally', 'Not interested', 'Only for specific genres'], 18, false, true),
('writer', 'What languages can you write in?', 'writing_languages', 'checkbox', ARRAY['English', 'Spanish', 'French', 'German', 'Italian', 'Portuguese', 'Mandarin', 'Japanese', 'Korean', 'Hindi', 'Arabic', 'Russian', 'Other'], 19, false, true),
('writer', 'Are you interested in mentoring other writers?', 'mentoring_interest', 'select', ARRAY['Very interested', 'Somewhat interested', 'Occasionally', 'Not interested', 'Only experienced writers'], 20, false, true);

-- Director Questions (20 questions with comprehensive options)
INSERT INTO profile_questions (talent_type, question, field_name, field_type, options, "order", required, active) VALUES
('director', 'What type of directing do you specialize in?', 'directing_specialization', 'select', ARRAY['Feature Films', 'Short Films', 'Television Series', 'Television Movies', 'Commercials', 'Music Videos', 'Documentaries', 'Web Series', 'Theater', 'Corporate Videos', 'Educational Videos', 'Live Events', 'Other'], 1, true, true),
('director', 'What genres do you direct? (Select all that apply)', 'directing_genres', 'checkbox', ARRAY['Drama', 'Comedy', 'Thriller', 'Horror', 'Romance', 'Science Fiction', 'Fantasy', 'Mystery', 'Action', 'Documentary', 'Biography', 'Historical', 'Animation', 'Musical', 'Western', 'Crime', 'Adventure', 'Family', 'Other'], 2, true, true),
('director', 'How many years of directing experience do you have?', 'directing_experience_years', 'select', ARRAY['Less than 1 year', '1-2 years', '3-5 years', '6-10 years', '11-15 years', '16-20 years', 'More than 20 years'], 3, true, true),
('director', 'What is your educational background in film/directing?', 'directing_education', 'select', ARRAY['Film School (Bachelor''s)', 'Film School (Master''s)', 'Film School (Certificate)', 'Theater/Drama School', 'Self-Taught', 'Workshops/Masterclasses', 'Assistant Director Experience', 'Other Film Studies', 'No formal education'], 4, true, true),
('director', 'How many projects have you directed?', 'projects_directed', 'select', ARRAY['1-2 projects', '3-5 projects', '6-10 projects', '11-20 projects', '21-50 projects', 'More than 50 projects'], 5, true, true),
('director', 'What is your preferred crew size?', 'preferred_crew_size', 'select', ARRAY['Solo/Minimal crew (1-3 people)', 'Small crew (4-10 people)', 'Medium crew (11-25 people)', 'Large crew (26-50 people)', 'Full production crew (50+ people)', 'Flexible based on project'], 6, false, true),
('director', 'Are you a member of any directing organizations?', 'directing_organizations', 'checkbox', ARRAY['Directors Guild of America (DGA)', 'International Documentary Association', 'Film Independent', 'Local Film Societies', 'Women in Film', 'Minority Film Organizations', 'Student Film Organizations', 'Other'], 7, false, true),
('director', 'What camera systems are you experienced with?', 'camera_systems', 'checkbox', ARRAY['RED Cameras', 'ARRI Alexa', 'Blackmagic', 'Canon (Cinema EOS)', 'Sony (FX Series)', 'Panasonic (Lumix/EVA)', 'Film Cameras (16mm/35mm)', 'DSLR/Mirrorless', 'iPhone/Mobile', 'Other'], 8, false, true),
('director', 'Do you have experience with post-production?', 'post_production_experience', 'select', ARRAY['Extensive experience', 'Moderate experience', 'Basic knowledge', 'Limited experience', 'No experience'], 9, false, true),
('director', 'What is your approach to working with actors?', 'actor_direction_style', 'textarea', NULL, 10, false, true),
('director', 'Are you comfortable directing in multiple languages?', 'multilingual_directing', 'select', ARRAY['Yes, fluent in multiple languages', 'Yes, with translation support', 'Limited to English', 'Willing to learn', 'Not comfortable'], 11, false, true),
('director', 'What is your experience with different shooting formats?', 'shooting_formats', 'checkbox', ARRAY['Digital Video', 'Film (16mm)', 'Film (35mm)', 'IMAX', 'VR/360', 'Live Streaming', 'Multi-Camera', 'Single Camera', 'Documentary Style', 'Studio Production'], 12, false, true),
('director', 'Do you have experience with visual effects supervision?', 'vfx_experience', 'select', ARRAY['Extensive VFX experience', 'Moderate VFX experience', 'Basic VFX knowledge', 'Limited VFX experience', 'No VFX experience'], 13, false, true),
('director', 'What is your preferred project budget range?', 'budget_preference', 'select', ARRAY['Micro-budget (Under $10k)', 'Low-budget ($10k-$100k)', 'Mid-budget ($100k-$1M)', 'High-budget ($1M-$10M)', 'Studio-level ($10M+)', 'Flexible based on project'], 14, false, true),
('director', 'Are you available for television directing?', 'television_availability', 'select', ARRAY['Yes, prefer television', 'Yes, open to television', 'Occasionally', 'Not interested', 'Only specific types of shows'], 15, false, true),
('director', 'What is your experience with directing children/minors?', 'children_directing', 'select', ARRAY['Extensive experience', 'Some experience', 'Limited experience', 'No experience but interested', 'Not comfortable with minors'], 16, false, true),
('director', 'Do you have experience with documentary filmmaking?', 'documentary_experience', 'select', ARRAY['Documentary specialist', 'Some documentary experience', 'Limited documentary work', 'No documentary experience', 'Not interested in documentaries'], 17, false, true),
('director', 'Are you comfortable with improvisation during filming?', 'improvisation_comfort', 'select', ARRAY['Love improvisation', 'Comfortable with improvisation', 'Somewhat comfortable', 'Prefer scripted work', 'Not comfortable with improvisation'], 18, false, true),
('director', 'What is your typical pre-production timeline?', 'preproduction_timeline', 'select', ARRAY['1-2 weeks', '3-4 weeks', '1-2 months', '3-4 months', '5-6 months', 'More than 6 months', 'Depends on project scope'], 19, false, true),
('director', 'Are you interested in mentoring other directors?', 'mentoring_interest', 'select', ARRAY['Very interested', 'Somewhat interested', 'Occasionally', 'Not interested', 'Only experienced directors'], 20, false, true);

-- Cinematographer Questions (20 questions with comprehensive options)
INSERT INTO profile_questions (talent_type, question, field_name, field_type, options, "order", required, active) VALUES
('cinematographer', 'What type of cinematography do you specialize in?', 'cinematography_specialization', 'select', ARRAY['Feature Films', 'Short Films', 'Television Series', 'Television Movies', 'Commercials', 'Music Videos', 'Documentaries', 'Web Series', 'Corporate Videos', 'Wedding Videos', 'Event Coverage', 'Live Streaming', 'Other'], 1, true, true),
('cinematographer', 'What camera systems do you own or have extensive experience with?', 'camera_expertise', 'checkbox', ARRAY['RED Cameras (Weapon, Epic, etc.)', 'ARRI Alexa (Mini, LF, etc.)', 'Blackmagic (Ursa, Pocket, etc.)', 'Canon Cinema EOS (C300, C500, etc.)', 'Sony FX Series (FX9, FX6, etc.)', 'Panasonic (EVA1, GH5, etc.)', 'Film Cameras (16mm/35mm)', 'DSLR/Mirrorless', 'Drone Cameras', 'Action Cameras', 'Other'], 2, true, true),
('cinematographer', 'How many years of cinematography experience do you have?', 'cinematography_experience_years', 'select', ARRAY['Less than 1 year', '1-2 years', '3-5 years', '6-10 years', '11-15 years', '16-20 years', 'More than 20 years'], 3, true, true),
('cinematographer', 'What is your educational background in cinematography?', 'cinematography_education', 'select', ARRAY['Film School (Bachelor''s)', 'Film School (Master''s)', 'Film School (Certificate)', 'Photography School', 'Self-Taught', 'Workshops/Masterclasses', 'Assistant Camera Experience', 'Other Film Studies', 'No formal education'], 4, true, true),
('cinematographer', 'Do you own your own camera equipment?', 'equipment_ownership', 'select', ARRAY['Full camera package', 'Camera body only', 'Lenses only', 'Basic equipment', 'No equipment', 'Rent as needed'], 5, true, true),
('cinematographer', 'What lighting equipment do you have access to?', 'lighting_equipment', 'checkbox', ARRAY['LED Panels', 'Tungsten Lights', 'HMI Lights', 'Fluorescent Lights', 'Practical Lights', 'Softboxes', 'Reflectors', 'Flags/Cutters', 'C-Stands', 'Light Meters', 'Color Meters', 'Other'], 6, false, true),
('cinematographer', 'Are you a member of any cinematography organizations?', 'cinematography_organizations', 'checkbox', ARRAY['International Cinematographers Guild (ICG)', 'American Society of Cinematographers (ASC)', 'Society of Camera Operators (SOC)', 'International Association of Cinematographers (IMAGO)', 'Local Film Organizations', 'Student Film Organizations', 'Other'], 7, false, true),
('cinematographer', 'What genres do you prefer to shoot?', 'preferred_genres', 'checkbox', ARRAY['Drama', 'Comedy', 'Thriller', 'Horror', 'Romance', 'Science Fiction', 'Fantasy', 'Mystery', 'Action', 'Documentary', 'Biography', 'Historical', 'Animation', 'Musical', 'Western', 'Crime', 'Adventure', 'Family', 'Other'], 8, false, true),
('cinematographer', 'Do you have experience with color grading?', 'color_grading_experience', 'select', ARRAY['Advanced color grading skills', 'Intermediate color grading', 'Basic color grading', 'Limited experience', 'No color grading experience'], 9, false, true),
('cinematographer', 'What is your experience with different shooting formats?', 'shooting_formats', 'checkbox', ARRAY['4K Digital', '6K Digital', '8K Digital', 'Raw Recording', 'ProRes', 'Film (16mm)', 'Film (35mm)', 'IMAX', 'VR/360', 'Anamorphic', 'Super 16', 'Other'], 10, false, true),
('cinematographer', 'Are you comfortable operating steadicam/gimbal systems?', 'stabilization_systems', 'select', ARRAY['Expert steadicam operator', 'Experienced with gimbals', 'Basic stabilization skills', 'Limited experience', 'Not experienced with stabilization'], 11, false, true),
('cinematographer', 'What is your preferred project budget range?', 'budget_preference', 'select', ARRAY['Micro-budget (Under $10k)', 'Low-budget ($10k-$100k)', 'Mid-budget ($100k-$1M)', 'High-budget ($1M-$10M)', 'Studio-level ($10M+)', 'Flexible based on project'], 12, false, true),
('cinematographer', 'Do you have drone piloting experience/certification?', 'drone_experience', 'select', ARRAY['FAA Part 107 certified', 'Drone pilot (no certification)', 'Some drone experience', 'No drone experience', 'Not interested in drone work'], 13, false, true),
('cinematographer', 'Are you experienced with underwater cinematography?', 'underwater_experience', 'select', ARRAY['Certified underwater cinematographer', 'Some underwater experience', 'Limited underwater work', 'No underwater experience', 'Not interested in underwater work'], 14, false, true),
('cinematographer', 'What is your experience with live event coverage?', 'live_event_experience', 'select', ARRAY['Extensive live event experience', 'Some live event work', 'Limited live event experience', 'No live event experience', 'Not interested in live events'], 15, false, true),
('cinematographer', 'Do you have experience with multi-camera setups?', 'multicamera_experience', 'select', ARRAY['Expert in multi-camera', 'Experienced with multi-camera', 'Basic multi-camera knowledge', 'Limited multi-camera experience', 'Single camera only'], 16, false, true),
('cinematographer', 'What is your experience with visual effects supervision?', 'vfx_supervision', 'select', ARRAY['VFX cinematography specialist', 'Some VFX experience', 'Basic VFX knowledge', 'Limited VFX experience', 'No VFX experience'], 17, false, true),
('cinematographer', 'Are you available for international travel?', 'travel_availability', 'select', ARRAY['Yes, love to travel', 'Yes, with advance notice', 'Occasionally', 'Local work only', 'Not available for travel'], 18, false, true),
('cinematographer', 'What is your typical turnaround time for a project?', 'project_turnaround', 'select', ARRAY['1-2 days', '3-5 days', '1-2 weeks', '3-4 weeks', '1-2 months', 'More than 2 months', 'Depends on project scope'], 19, false, true),
('cinematographer', 'Are you interested in mentoring other cinematographers?', 'mentoring_interest', 'select', ARRAY['Very interested', 'Somewhat interested', 'Occasionally', 'Not interested', 'Only experienced cinematographers'], 20, false, true);

-- Update the talent type options in job creation and other relevant places
-- This will be handled dynamically by the application